project_id = "veedztdijmscebgadzyx"

[functions.generate-template-images]
verify_jwt = false

[functions.telegram-bot-webhook]
verify_jwt = false

[functions.send-bot-message]
verify_jwt = false

[functions.playground-form-submit]
verify_jwt = false

[functions.send-document-email]
verify_jwt = false

[functions.sales-assistant]
verify_jwt = false

[functions.check-overdue]
verify_jwt = false